allowBuilds:
  "@google/genai": true
  browser-tabs-lock: true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  workerd: true
# Error when package manager version does not match package.json
pmOnFail: error
