// This file is auto-generated by @hey-api/openapi-ts

export type Body_create_wearable = {
    category: string;
    description: (string | null);
    image: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Outfit = {
    id: string;
    top: Wearable;
    bottom: Wearable;
};

export type User = {
    id: string;
    name: string;
    avatar_image_url: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Wearable = {
    id: string;
    category: string;
    description: (string | null);
    wearable_image_url: string;
    generation_status: 'pending' | 'completed';
};

export type generation_status = 'pending' | 'completed';

export type GetUsersResponse = (Array<User>);

export type GetUsersError = unknown;

export type GetAvatarImageData = {
    path: {
        avatar_image_id: string;
    };
};

export type GetAvatarImageResponse = ((Blob | File));

export type GetAvatarImageError = (HTTPValidationError);

export type GetWearablesResponse = (Array<Wearable>);

export type GetWearablesError = unknown;

export type CreateWearableData = {
    body: Body_create_wearable;
};

export type CreateWearableResponse = (Wearable);

export type CreateWearableError = (HTTPValidationError);

export type GetWearableImageData = {
    path: {
        wearable_image_id: string;
    };
};

export type GetWearableImageResponse = ((Blob | File));

export type GetWearableImageError = (HTTPValidationError);

export type GetOutfitData = {
    query: {
        bottom_id: string;
        top_id: string;
    };
};

export type GetOutfitResponse = ((Blob | File));

export type GetOutfitError = (HTTPValidationError);

export type GetOutfitsResponse = (Array<Outfit>);

export type GetOutfitsError = unknown;

export type CreateOutfitData = {
    query: {
        bottom_id: string;
        top_id: string;
    };
};

export type CreateOutfitResponse = (unknown);

export type CreateOutfitError = (HTTPValidationError);

export type DeleteOutfitData = {
    query: {
        id: string;
    };
};

export type DeleteOutfitResponse = (unknown);

export type DeleteOutfitError = (HTTPValidationError);