// This file is auto-generated by @hey-api/openapi-ts

export type APIOutfit = {
  id: string;
  top: APIWearable;
  bottom: APIWearable;
};

export type APIUser = {
  id: string;
  name: string;
  avatar_image_url: string;
};

export type APIWearable = {
  id: string;
  category: string;
  description: string | null;
  wearable_image_url: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type GetUsersResponse = Array<APIUser>;

export type GetUsersError = unknown;

export type GetAvatarImageData = {
  path: {
    avatar_image_id: string;
  };
};

export type GetAvatarImageResponse = Blob | File;

export type GetAvatarImageError = HTTPValidationError;

export type GetWearablesResponse = Array<APIWearable>;

export type GetWearablesError = unknown;

export type GetWearableImageData = {
  path: {
    wearable_image_id: string;
  };
};

export type GetWearableImageResponse = Blob | File;

export type GetWearableImageError = HTTPValidationError;

export type GetOutfitData = {
  query: {
    bottom_id: string;
    top_id: string;
  };
};

export type GetOutfitResponse = Blob | File;

export type GetOutfitError = HTTPValidationError;

export type GetOutfitsResponse = Array<APIOutfit>;

export type GetOutfitsError = unknown;

export type AddOutfitData = {
  query: {
    bottom_id: string;
    top_id: string;
  };
};

export type AddOutfitResponse = unknown;

export type AddOutfitError = HTTPValidationError;

export type RemoveOutfitData = {
  query: {
    id: string;
  };
};

export type RemoveOutfitResponse = unknown;

export type RemoveOutfitError = unknown | HTTPValidationError;
