// This file is auto-generated by @hey-api/openapi-ts

export type BodyCreateWearables = {
    category: Array<string>;
    description: Array<string>;
    image: Array<Blob | File>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Outfit = {
    id: string;
    top: Wearable;
    bottom: Wearable;
};

export type User = {
    id: string;
    name: string;
    avatar_image_url: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type Wearable = {
    id: string;
    category: string;
    description: string | null;
    wearable_image_url: string;
    generation_status: 'pending' | 'completed';
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Successful Response
     */
    200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetAvatarImageData = {
    body?: never;
    path: {
        avatar_image_id: string;
    };
    query?: never;
    url: '/images/avatars/{avatar_image_id}';
};

export type GetAvatarImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAvatarImageError = GetAvatarImageErrors[keyof GetAvatarImageErrors];

export type GetAvatarImageResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type GetAvatarImageResponse = GetAvatarImageResponses[keyof GetAvatarImageResponses];

export type GetWearablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wearables';
};

export type GetWearablesResponses = {
    /**
     * Successful Response
     */
    200: Array<Wearable>;
};

export type GetWearablesResponse = GetWearablesResponses[keyof GetWearablesResponses];

export type CreateWearablesData = {
    body: BodyCreateWearables;
    path?: never;
    query?: never;
    url: '/wearables';
};

export type CreateWearablesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWearablesError = CreateWearablesErrors[keyof CreateWearablesErrors];

export type CreateWearablesResponses = {
    /**
     * Successful Response
     */
    201: Array<Wearable>;
};

export type CreateWearablesResponse = CreateWearablesResponses[keyof CreateWearablesResponses];

export type GetWearableImageData = {
    body?: never;
    path: {
        wearable_image_id: string;
    };
    query?: never;
    url: '/images/wearables/{wearable_image_id}';
};

export type GetWearableImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWearableImageError = GetWearableImageErrors[keyof GetWearableImageErrors];

export type GetWearableImageResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type GetWearableImageResponse = GetWearableImageResponses[keyof GetWearableImageResponses];

export type GetOutfitData = {
    body?: never;
    path?: never;
    query: {
        top_id: string;
        bottom_id: string;
    };
    url: '/images/outfit';
};

export type GetOutfitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOutfitError = GetOutfitErrors[keyof GetOutfitErrors];

export type GetOutfitResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type GetOutfitResponse = GetOutfitResponses[keyof GetOutfitResponses];

export type DeleteOutfitData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/outfits';
};

export type DeleteOutfitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOutfitError = DeleteOutfitErrors[keyof DeleteOutfitErrors];

export type DeleteOutfitResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetOutfitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/outfits';
};

export type GetOutfitsResponses = {
    /**
     * Successful Response
     */
    200: Array<Outfit>;
};

export type GetOutfitsResponse = GetOutfitsResponses[keyof GetOutfitsResponses];

export type CreateOutfitData = {
    body?: never;
    path?: never;
    query: {
        top_id: string;
        bottom_id: string;
    };
    url: '/outfits';
};

export type CreateOutfitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOutfitError = CreateOutfitErrors[keyof CreateOutfitErrors];

export type CreateOutfitResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};