// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options, formDataBodySerializer } from '@hey-api/client-fetch';
import type { HealthData, GetMeData, GetMeResponse, UpdateAvatarImageData, UpdateAvatarImageError, GetWearablesData, GetWearablesResponse, CreateWearablesData, CreateWearablesResponse, CreateWearablesError, DeleteOutfitData, DeleteOutfitError, GetOutfitsData, GetOutfitsResponse, CreateOutfitData, CreateOutfitError } from './types.gen';

export const client = createClient(createConfig({
    throwOnError: true
}));

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = true>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
        ...options,
        url: '/healthz'
    });
};

/**
 * Get Me
 */
export const getMe = <ThrowOnError extends boolean = true>(options?: Options<GetMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMeResponse, unknown, ThrowOnError>({
        ...options,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me'
    });
};

/**
 * Update Avatar Image
 */
export const updateAvatarImage = <ThrowOnError extends boolean = true>(options: Options<UpdateAvatarImageData, ThrowOnError>) => {
    return (options?.client ?? client).put<unknown, UpdateAvatarImageError, ThrowOnError>({
        ...options,
        ...formDataBodySerializer,
        headers: {
            'Content-Type': null,
            ...options?.headers
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/images/avatars/me'
    });
};

/**
 * Get Wearables
 */
export const getWearables = <ThrowOnError extends boolean = true>(options?: Options<GetWearablesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetWearablesResponse, unknown, ThrowOnError>({
        ...options,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/wearables'
    });
};

/**
 * Create Wearables
 * Create one or more wearables.
 *
 * Multiple wearables can be created in one request by passing fields multiple times with the same
 * name. All fields must appear the same number of times. The description can be set to an empty
 * string if you want to omit it.
 */
export const createWearables = <ThrowOnError extends boolean = true>(options: Options<CreateWearablesData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateWearablesResponse, CreateWearablesError, ThrowOnError>({
        ...options,
        ...formDataBodySerializer,
        headers: {
            'Content-Type': null,
            ...options?.headers
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/wearables'
    });
};

/**
 * Delete Outfit
 */
export const deleteOutfit = <ThrowOnError extends boolean = true>(options: Options<DeleteOutfitData, ThrowOnError>) => {
    return (options?.client ?? client).delete<unknown, DeleteOutfitError, ThrowOnError>({
        ...options,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/outfits'
    });
};

/**
 * Get Outfits
 */
export const getOutfits = <ThrowOnError extends boolean = true>(options?: Options<GetOutfitsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetOutfitsResponse, unknown, ThrowOnError>({
        ...options,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/outfits'
    });
};

/**
 * Create Outfit
 */
export const createOutfit = <ThrowOnError extends boolean = true>(options: Options<CreateOutfitData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, CreateOutfitError, ThrowOnError>({
        ...options,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/outfits'
    });
};