// This file is auto-generated by @hey-api/openapi-ts

export type BodyCreateWearables = {
    category: Array<string>;
    description: Array<string>;
    image: Array<Blob | File>;
};

export type BodyUpdateAvatarImage = {
    image: Blob | File;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Outfit = {
    id: string;
    top: Wearable;
    bottom: Wearable;
};

export type User = {
    id: string;
    has_avatar_image: boolean;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type Wearable = {
    id: string;
    category: string;
    description: string | null;
    wearable_image_url: string;
    generation_status: 'pending' | 'completed';
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateAvatarImageData = {
    body: BodyUpdateAvatarImage;
    path?: never;
    query?: never;
    url: '/images/avatars/me';
};

export type UpdateAvatarImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAvatarImageError = UpdateAvatarImageErrors[keyof UpdateAvatarImageErrors];

export type UpdateAvatarImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWearablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wearables';
};

export type GetWearablesResponses = {
    /**
     * Successful Response
     */
    200: Array<Wearable>;
};

export type GetWearablesResponse = GetWearablesResponses[keyof GetWearablesResponses];

export type CreateWearablesData = {
    body: BodyCreateWearables;
    path?: never;
    query?: never;
    url: '/wearables';
};

export type CreateWearablesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWearablesError = CreateWearablesErrors[keyof CreateWearablesErrors];

export type CreateWearablesResponses = {
    /**
     * Successful Response
     */
    201: Array<Wearable>;
};

export type CreateWearablesResponse = CreateWearablesResponses[keyof CreateWearablesResponses];

export type GetWearableImageData = {
    body?: never;
    path: {
        wearable_image_id: string;
    };
    query?: never;
    url: '/images/wearables/{wearable_image_id}';
};

export type GetWearableImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWearableImageError = GetWearableImageErrors[keyof GetWearableImageErrors];

export type GetWearableImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetOutfitImageData = {
    body?: never;
    path?: never;
    query: {
        top_id: string;
        bottom_id: string;
    };
    url: '/images/outfit';
};

export type GetOutfitImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOutfitImageError = GetOutfitImageErrors[keyof GetOutfitImageErrors];

export type GetOutfitImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteOutfitData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/outfits';
};

export type DeleteOutfitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOutfitError = DeleteOutfitErrors[keyof DeleteOutfitErrors];

export type DeleteOutfitResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetOutfitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/outfits';
};

export type GetOutfitsResponses = {
    /**
     * Successful Response
     */
    200: Array<Outfit>;
};

export type GetOutfitsResponse = GetOutfitsResponses[keyof GetOutfitsResponses];

export type CreateOutfitData = {
    body?: never;
    path?: never;
    query: {
        top_id: string;
        bottom_id: string;
    };
    url: '/outfits';
};

export type CreateOutfitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOutfitError = CreateOutfitErrors[keyof CreateOutfitErrors];

export type CreateOutfitResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};